name: pyinstaller-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
    - name: PyInstaller build
      run: |
        pyinstaller -w -i=icon.ico --add-data icon.ico:. --add-data logo.png:. --add-data loading.gif:. --name CyBot --clean bot-gui.py
    - name: Get build files size
      run: ls -alshS dist/ | awk '{print $10 " => " $6}'
